language: python

python:
  - '3.6'

env:
  global:
    - PYENV_VERSION=3.6
    - PKG_TEST_PYTHON="--test-python=py36"
    - CHANS_DEV="-c pyviz/label/earthsim -c pyviz/label/dev -c erdc -c conda-forge"
    - CHANS_REL="-c pyviz -c erdc -c conda-forge"
    - MPLBACKEND="Agg"
    - LABELS_DEV="--label dev"
    - LABELS_REL="--label dev --label main"

# Turn off email notifications
notifications:
  email: false

matrix:
  include:
    - os: linux
      env: PYTHON_VERSION="3.6"
    - os: osx
      osx_image: xcode9.4
      env: PYTHON_VERSION="3.6"


# commands to install genesis
install:
  - conda env create -n test_env -f environment.yml
  - source activate test_env
  - python setup.py install
  - conda list

# command to run tests
script:
  - pytest
